### PR TITLE
Simplify Placenames ontology

### PR DESCRIPTION
**Pull request by dr-shorthair**
- remove deprecated properties
- remove asgs, gnaf, geofab classes
- renew documentation & multiple diagrams
- remove PROV, REG dependencies

See preview doco https://raw.githack.com/GeoscienceAustralia/Place-Names/simplify-issue19/placenames.html

### CODE REVIEW

**Review by nicholascar — APPROVED** [review]
Looks good

**Comment by nicholascar** [comment]
> Remove unused ns prefixes

Note that the next release of rdflib (5.0.0) that pyLODE will use is due in a fortnight and it will will finally clean up unused prefixes. Ashely and I are working on now! This has been a 3+ year fix for rdflib.

**Comment by dr-shorthair** [comment]
fixes #19

**Comment by dr-shorthair** [comment]
@ibastrak @bellie888 could you [look at this](https://raw.githack.com/GeoscienceAustralia/Place-Names/simplify-issue19/placenames.html) to decide if the older ontology should be replaced. This version conforms to [Rules for Loc-I datasets](http://loci.cat/loci-datasets.html)

**Review by bellie888 — APPROVED** [review]
I don't know much about the changes proposed, but rely on your skill and knowledge with these things - Joe

**Comment by dr-shorthair** [comment]
@bellie888 do you have the Place-type classification available?

**Comment by bellie888** [comment]
http://vocabs.ands.org.au/repository/api/lda/ga/place-type/v1-0/resource?uri=http://pid.geoscience.gov.au/def/voc/ga/PlaceType/ANCHORAGE

This is what the Placenames API points to from here:
http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/placenames-dataset/placename/AAD_4

There is place type, category and group.
There might be a classification document or html resource, Alex Ip showed us that sort of thing at one time. Shane and Jenny were working on this stuff before Christmas.

**Pull request merged**
