### PR TITLE
Informal names

### LINKED ISSUE #21: Place-name validity
'Period of validity' is yet to be implemented. 
Does this inhere in 
- the name
- the association of the name with the place (i.e. feature)

That will seriously affect the complexity of the model. The latter would require an association class.

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #21
See documentation at 
https://raw.githack.com/GeoscienceAustralia/Place-Names/informal-names/placenames.html

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Any comments on this @ibastrak @Shanecrossman
I have an interlocking web of PRs in geox, dggs, loci, placenames with cross dependencies.
Trying to keep concerns separated, but need to move some forward in order to deliver to GA.
Would be good to get some of them reviewed and merged.

**Comment by ibastrak** [comment]
I've got a bit lost between projects and issues but will try my best - may require some clarification :-)
I answered to two parts
Commit Summary
•	Make 'official place name' a specialization of 'place name' where the namer is a jurisdiction; 
- Agreed
•	Merge branch 'naming-authorities' into informal-names 
- Agreed, 'status' terms in the OfficialPlaceName vs freely floating 'status' in the PlaceName is still my question - if place is official it can be only one status by default: 'official'. do we need it there?

What is the next request to me and Shane?

**Comment by dr-shorthair** [comment]
The standard status values are [shown here](https://raw.githack.com/GeoscienceAustralia/Place-Names/informal-names/placenames.html#Status) etc as discussed with @Shanecrossman 

A `PlaceName` 
- may be named by anyone,
- has `status`=`informal` by default. 
- If `status`=`( gazetted | released | published | retired )`, then it is _implicitly_ an `OfficialPlaceName`. 

An `OfficialPlaceName` 
- must be named by a `PlaceNamingAuthority` 
- may _**not**_ have `status='informal'`
- must be in a gazetteer
- must have a `dateGazetted`
- may have dates corresponding to other lifecycle stages

**Comment by ibastrak** [comment]
Happy with this status explanation for now.

I still want to progress separation of historic from official/non-official in the list of values. If we progress to that, then a place name would be described in terms of two boolean values (in addition to indigenous) official/non-official and historic/current.

 I'll talk to Shane tomorrow-Friday about it and how difficult if might be to implement.

**Comment by dr-shorthair** [comment]
'Official' designation is implied in two ways
- optionally, by `rdf:type = OfficialPlaceName` see [example](https://raw.githack.com/GeoscienceAustralia/Place-Names/informal-names/placenames.html#Officialplace-name)
- canonically, by `status = ( gazetted | released | published | retired )`
  - this could be reinforced by either 
    1. adding an additional status value `official`, as a `broader` concept to `( gazetted | released | published | retired )`
    2. renaming `( gazetted | released | published | retired )` to `( official-gazetted | official-released | official-published | official-retired )`

But I really don't think another property is needed. The information is there. An additional flag or property would just provide scope for inconsistencies to creep into the data. I suggest choosing either 1. or 2. would be fine.

**Comment by dr-shorthair** [comment]
I've taken option (a) for the moment - this is probably the best solution - embedding structure in identifiers (pattern b) is considered harmful ;-)

**Pull request merged**
